### PR TITLE
Added Russian localization

### PR DESCRIPTION
**Pull request by SyberiaKey**

### CODE REVIEW

**Review by wafflecoffee — APPROVED** [review]
It looks good, thank you! I'll be releasing a new version soon.

**Comment by wafflecoffee** [comment]
https://modrinth.com/mod/wake-up-time/version/1.0.1

**Comment by SyberiaKey** [comment]
Thank you :)

**Comment by SyberiaKey** [comment]
Oh, i found one mistake xd
изображение

**Comment by wafflecoffee** [comment]
A fixed version can be found at https://github.com/emmods/wake-up-time/suites/6421089214/artifacts/234488440, but I'm not going to make a release for that until I find time to add #1

**Pull request merged**
